# Site settings
title: Steven Chen
email: stevenchen@utexas.edu
description: > 
    Hello, I'm Steven Chen! I'm currently a Masters student
    in Computer Science at Stanford.
baseurl: "" 
url: "http://stevenzc.com" 
github_username:  stevenzchen
linkedin_username: stevenzchen
facebook_username: stevenzchen
steam_username: stevenzc


# Build settings
markdown: kramdown
