# Site settings
title: Steven Chen
email: stevenzc3@gmail.com
description: > 
    Hello, I'm Steven! I'm currently a Stanford Computer Science graduate student.
baseurl: "" 
url: "http://stevenzc.com" 
github_username:  stevenzchen
linkedin_username: stevenzchen
facebook_username: stevenzchen
steam_username: stevenzc


# Build settings
markdown: kramdown
